import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Cabin } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  weight: ["400", "600"],
  subsets: ["cyrillic", "latin"],
  variable: "--font-inter",
  display: "swap",
});

const cabin = Cabin({
  weight: ["500"],
  subsets: ["latin"],
  variable: "--font-cabin",
  display: "swap",
  style: "normal",
});

const geometria = localFont({
  src: [
    {
      path: '../../public/fonts/Geometria/Geometria-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Geometria/Geometria-Bold.woff2',
      weight: '700',
      style: 'normal',
    }
  ],
  variable: "--font-geometria",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${geometria.variable} ${cabin.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
